include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/.symlinks/**
    - .dart_tool/**
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning

linter:
  rules:
    # стиль кода
    prefer_single_quotes: true
    directives_ordering: true
    sort_constructors_first: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true

    # flutter-специфика
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # безопасность и читаемость
    avoid_print: true
    avoid_unnecessary_containers: true
    unnecessary_late: true
